DROP DATABASE IF EXISTS hotel;

CREATE USER hotel_adm WITH PASSWORD 'Zz20164209';
CREATE DATABASE hotel;
\connect hotel
GRANT ALL PRIVILEGES ON DATABASE hotel TO hotel_adm;

CREATE TABLE Employees (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  surename VARCHAR NOT NULL
);

CREATE TABLE Hotels (
  id SERIAL PRIMARY KEY ,
  city VARCHAR NOT NULL ,
  address VARCHAR NOT NULL
);

CREATE TABLE Users (
  id INTEGER REFERENCES Employees ON DELETE CASCADE,
  login VARCHAR PRIMARY KEY,
  password VARCHAR
);

CREATE TABLE Administrators (
  login VARCHAR PRIMARY KEY REFERENCES Users ON DELETE CASCADE ,
  hotel_id INTEGER REFERENCES Hotels ON DELETE CASCADE
);

CREATE TABLE Owners (
  login VARCHAR PRIMARY KEY REFERENCES Users ON DELETE CASCADE
);

CREATE TABLE Staff (
  id INTEGER PRIMARY KEY REFERENCES Employees ON DELETE CASCADE ,
  hotel_id INTEGER REFERENCES Hotels ON DELETE CASCADE
);

CREATE TABLE Rooms (
  id INTEGER REFERENCES Hotels ON DELETE CASCADE ,
  number INTEGER NOT NULL CHECK (number > 0) ,
  capacity INTEGER NOT NULL ,
  PRIMARY KEY (id, number)
);

CREATE TABLE EKeys (
  id SERIAL PRIMARY KEY
);

CREATE TABLE Guest (
  id SERIAL PRIMARY KEY ,
  name VARCHAR NOT NULL ,
  surename VARCHAR NOT NULL ,
  doc VARCHAR NOT NULL
);

CREATE TABLE EmployeesKeys (
  id INTEGER REFERENCES Employees ON DELETE CASCADE ,
  key_id INTEGER REFERENCES EKeys ON DELETE CASCADE ,
  PRIMARY KEY (id, key_id)
);

CREATE TABLE HotelsOwners (
  login VARCHAR REFERENCES Owners ON DELETE CASCADE ,
  hotel_id INTEGER REFERENCES Hotels ON DELETE CASCADE ,
  PRIMARY KEY (login, hotel_id)
);

CREATE TABLE RoomsKeys (
  hotel_id INTEGER ,
  number INTEGER ,
  key_id INTEGER REFERENCES EKeys ON DELETE CASCADE ,
  FOREIGN KEY (hotel_id, number) REFERENCES Rooms ON DELETE CASCADE ,
  PRIMARY KEY (hotel_id, number, key_id)
);